[theme]
primaryColor = "#10B981"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3F4F6"
textColor = "#1F2937"
font = "sans serif"

[client]
showErrorDetails = true

[server]
maxUploadSize = 50
enableXsrfProtection = true
